BEGIN
   DBMS_WM.grantsystempriv(
      priv_types => 'ACCESS_ANY_WORKSPACE, MERGE_ANY_WORKSPACE, CREATE_ANY_WORKSPACE, REMOVE_ANY_WORKSPACE, ROLLBACK_ANY_WORKSPACE, WM_ADMIN'
    , grantee    => 'HR_WM');
END;
/