/* This anonymous block creates a table named EMPLOYEES
   PL/SQL Block is restartable, so it can be executed n times, but
   only creates the table if it does not exist.
   %author  ABO
   %created 2017-04-19 22:34:31
 */

BEGIN
   FOR i IN (SELECT 'EMPLOYEES' AS table_name FROM DUAL
             MINUS
             SELECT table_name FROM user_tables)
   LOOP
      EXECUTE IMMEDIATE q'[
  CREATE TABLE "EMPLOYEES" 
   (	
    "EMPLOYEE_ID" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(20), 
	"LAST_NAME" VARCHAR2(25) CONSTRAINT "EMPLOYEES_NN04" NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(25) CONSTRAINT "EMPLOYEES_NN01" NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20), 
	"HIRE_DATE" DATE CONSTRAINT "EMPLOYEES_NN02" NOT NULL ENABLE, 
	"JOB_ID" VARCHAR2(10) CONSTRAINT "EMPLOYEES_NN03" NOT NULL ENABLE, 
	"SALARY" NUMBER(8,2), 
	"COMMISSION_PCT" NUMBER(2,2), 
	"MANAGER_ID" NUMBER(6,0), 
	"DEPARTMENT_ID" NUMBER(4,0), 
	 CONSTRAINT "EMPLOYEES_CK" CHECK (salary > 0) ENABLE, 
	 CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EMPLOYEES_UQ" UNIQUE ("EMAIL")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EMPLOYEES_FK01" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID") ENABLE, 
	 CONSTRAINT "EMPLOYEES_FK02" FOREIGN KEY ("JOB_ID")
	  REFERENCES "JOBS" ("JOB_ID") ENABLE, 
	 CONSTRAINT "EMPLOYEES_FK03" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "EMPLOYEES" ("EMPLOYEE_ID") ENABLE
   ) 
   ]';
   END LOOP;
END;
/